//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : PVI_ProyectoFinal
	/// Data Source    : DESKTOP-06SFANS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class PviProyectoFinalDB : LinqToDB.Data.DataConnection
	{
		public ITable<Bitacora>     Bitacoras      { get { return this.GetTable<Bitacora>(); } }
		public ITable<Casa>         Casas          { get { return this.GetTable<Casa>(); } }
		public ITable<Categoria>    Categorias     { get { return this.GetTable<Categoria>(); } }
		public ITable<Cobro>        Cobros         { get { return this.GetTable<Cobro>(); } }
		public ITable<DetalleCobro> DetalleCobroes { get { return this.GetTable<DetalleCobro>(); } }
		public ITable<Persona>      Personas       { get { return this.GetTable<Persona>(); } }
		public ITable<Servicio>     Servicios      { get { return this.GetTable<Servicio>(); } }

		public PviProyectoFinalDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PviProyectoFinalDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PviProyectoFinalDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PviProyectoFinalDB(DataOptions<PviProyectoFinalDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("id_bitacora"), PrimaryKey, Identity] public int      IdBitacora { get; set; } // int
		[Column("detalle"),     NotNull             ] public string   Detalle    { get; set; } // varchar(255)
		[Column("id_cobro"),    NotNull             ] public int      IdCobro    { get; set; } // int
		[Column("id_user"),     NotNull             ] public int      IdUser     { get; set; } // int
		[Column("fecha"),       NotNull             ] public DateTime Fecha      { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK__Cobros__id_bitac__45F365D3_BackReference (dbo.Cobros)
		/// </summary>
		[Association(ThisKey="IdBitacora", OtherKey="IdBitacora", CanBeNull=true)]
		public IEnumerable<Cobro> Cobrosidbitac45F365D { get; set; }

		/// <summary>
		/// FK__Bitacora__id_cob__440B1D61 (dbo.Cobros)
		/// </summary>
		[Association(ThisKey="IdCobro", OtherKey="IdCobro", CanBeNull=false)]
		public Cobro Idcob440B1D { get; set; }

		/// <summary>
		/// FK__Bitacora__id_use__44FF419A (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdUser", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Iduse44FF419A { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Casas")]
	public partial class Casa
	{
		[Column("id_casa"),             PrimaryKey, Identity] public int      IdCasa             { get; set; } // int
		[Column("nombre_casa"),         NotNull             ] public string   NombreCasa         { get; set; } // nvarchar(255)
		[Column("metros_cuadrados"),    NotNull             ] public int      MetrosCuadrados    { get; set; } // int
		[Column("numero_habitaciones"), NotNull             ] public int      NumeroHabitaciones { get; set; } // int
		[Column("numero_banos"),        NotNull             ] public int      NumeroBanos        { get; set; } // int
		[Column("precio"),              NotNull             ] public decimal  Precio             { get; set; } // decimal(15, 2)
		[Column("id_persona"),          NotNull             ] public int      IdPersona          { get; set; } // int
		[Column("fecha_construccion"),  NotNull             ] public DateTime FechaConstruccion  { get; set; } // date
		[Column("estado"),              NotNull             ] public bool     Estado             { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__Cobros__id_casa__412EB0B6_BackReference (dbo.Cobros)
		/// </summary>
		[Association(ThisKey="IdCasa", OtherKey="IdCasa", CanBeNull=true)]
		public IEnumerable<Cobro> Cobrosidcasa412EB0B { get; set; }

		/// <summary>
		/// FK__Casas__id_person__3E52440B (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Idperson3E52440B { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Categorias")]
	public partial class Categoria
	{
		[Column("id_categoria"), PrimaryKey,  Identity] public int    IdCategoria { get; set; } // int
		[Column("nombre"),       NotNull              ] public string Nombre      { get; set; } // varchar(100)
		[Column("descripcion"),     Nullable          ] public string Descripcion { get; set; } // text
		[Column("estado"),       NotNull              ] public bool   Estado      { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__Servicios__id_ca__4E88ABD4_BackReference (dbo.Servicios)
		/// </summary>
		[Association(ThisKey="IdCategoria", OtherKey="IdCategoria", CanBeNull=true)]
		public IEnumerable<Servicio> Serviciosidca4E88Abds { get; set; }

		/// <summary>
		/// FK__Servicios__id_ca__72C60C4A_BackReference (dbo.Servicios)
		/// </summary>
		[Association(ThisKey="IdCategoria", OtherKey="IdCategoria", CanBeNull=true)]
		public IEnumerable<Servicio> Serviciosidca72C60C4A { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Cobros")]
	public partial class Cobro
	{
		[Column("id_cobro"),     PrimaryKey,  Identity] public int       IdCobro     { get; set; } // int
		[Column("id_casa"),      NotNull              ] public int       IdCasa      { get; set; } // int
		[Column("mes"),          NotNull              ] public int       Mes         { get; set; } // int
		[Column("anno"),         NotNull              ] public int       Anno        { get; set; } // int
		[Column("id_bitacora"),     Nullable          ] public int?      IdBitacora  { get; set; } // int
		[Column("estado"),       NotNull              ] public string    Estado      { get; set; } // varchar(50)
		[Column("monto"),        NotNull              ] public decimal   Monto       { get; set; } // decimal(15, 2)
		[Column("fecha_pagada"),    Nullable          ] public DateTime? FechaPagada { get; set; } // date

		#region Associations

		/// <summary>
		/// FK__Bitacora__id_cob__440B1D61_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdCobro", OtherKey="IdCobro", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoraidcob440B1D { get; set; }

		/// <summary>
		/// FK__DetalleCo__id_co__49C3F6B7_BackReference (dbo.DetalleCobro)
		/// </summary>
		[Association(ThisKey="IdCobro", OtherKey="IdCobro", CanBeNull=true)]
		public IEnumerable<DetalleCobro> DetalleCoidco49C3F6B { get; set; }

		/// <summary>
		/// FK__Cobros__id_bitac__45F365D3 (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdBitacora", OtherKey="IdBitacora", CanBeNull=true)]
		public Bitacora Idbitac45F365D { get; set; }

		/// <summary>
		/// FK__Cobros__id_casa__412EB0B6 (dbo.Casas)
		/// </summary>
		[Association(ThisKey="IdCasa", OtherKey="IdCasa", CanBeNull=false)]
		public Casa Idcasa412EB0B { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="DetalleCobro")]
	public partial class DetalleCobro
	{
		[Column("servicio"), PrimaryKey(1), NotNull] public int Servicio { get; set; } // int
		[Column("id_cobro"), PrimaryKey(2), NotNull] public int IdCobro  { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__DetalleCo__id_co__49C3F6B7 (dbo.Cobros)
		/// </summary>
		[Association(ThisKey="IdCobro", OtherKey="IdCobro", CanBeNull=false)]
		public Cobro DetalleCoidco49C3F6B { get; set; }

		/// <summary>
		/// FK__DetalleCo__servi__48CFD27E (dbo.Servicios)
		/// </summary>
		[Association(ThisKey="Servicio", OtherKey="IdServicio", CanBeNull=false)]
		public Servicio DetalleCoservi48CFD27E { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Persona")]
	public partial class Persona
	{
		[Column("id_persona"),       PrimaryKey,  Identity] public int       IdPersona       { get; set; } // int
		[Column("nombre"),           NotNull              ] public string    Nombre          { get; set; } // varchar(100)
		[Column("apellido"),         NotNull              ] public string    Apellido        { get; set; } // varchar(100)
		[Column("email"),            NotNull              ] public string    Email           { get; set; } // varchar(150)
		[Column("telefono"),            Nullable          ] public string    Telefono        { get; set; } // varchar(15)
		[Column("direccion"),           Nullable          ] public string    Direccion       { get; set; } // varchar(255)
		[Column("fecha_nacimiento"),    Nullable          ] public DateTime? FechaNacimiento { get; set; } // date
		[Column("contrasena"),          Nullable          ] public string    Contrasena      { get; set; } // varchar(255)
		[Column("estado"),              Nullable          ] public bool?     Estado          { get; set; } // bit
		[Column("tipo_persona"),        Nullable          ] public string    TipoPersona     { get; set; } // varchar(50)

		#region Associations

		/// <summary>
		/// FK__Bitacora__id_use__44FF419A_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdUser", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoraiduse44FF419A { get; set; }

		/// <summary>
		/// FK__Casas__id_person__3E52440B_BackReference (dbo.Casas)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Casa> Casasidperson3E52440B { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Servicios")]
	public partial class Servicio
	{
		[Column("id_servicio"),  PrimaryKey,  Identity] public int     IdServicio  { get; set; } // int
		[Column("nombre"),       NotNull              ] public string  Nombre      { get; set; } // varchar(100)
		[Column("descripcion"),     Nullable          ] public string  Descripcion { get; set; } // text
		[Column("precio"),       NotNull              ] public decimal Precio      { get; set; } // decimal(10, 2)
		[Column("id_categoria"), NotNull              ] public int     IdCategoria { get; set; } // int
		[Column("estado"),       NotNull              ] public bool    Estado      { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK__DetalleCo__servi__48CFD27E_BackReference (dbo.DetalleCobro)
		/// </summary>
		[Association(ThisKey="IdServicio", OtherKey="Servicio", CanBeNull=true)]
		public IEnumerable<DetalleCobro> DetalleCoservi48CFD27E { get; set; }

		/// <summary>
		/// FK__Servicios__id_ca__4E88ABD4 (dbo.Categorias)
		/// </summary>
		[Association(ThisKey="IdCategoria", OtherKey="IdCategoria", CanBeNull=false)]
		public Categoria Idca4E88ABD { get; set; }

		/// <summary>
		/// FK__Servicios__id_ca__72C60C4A (dbo.Categorias)
		/// </summary>
		[Association(ThisKey="IdCategoria", OtherKey="IdCategoria", CanBeNull=false)]
		public Categoria Idca72C60C4A { get; set; }

		#endregion
	}

	public static partial class PviProyectoFinalDBStoredProcedures
	{
		#region SpActualizarServicio

		public static int SpActualizarServicio(this PviProyectoFinalDB dataConnection, int? @IdServicio, string @Nombre, string @Descripcion, decimal? @Precio, int? @IdCategoria)
		{
			var parameters = new []
			{
				new DataParameter("@IdServicio",  @IdServicio,  LinqToDB.DataType.Int32),
				new DataParameter("@Nombre",      @Nombre,      LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@Descripcion", @Descripcion, LinqToDB.DataType.Text)
				{
					Size = 2147483647
				},
				new DataParameter("@Precio",      @Precio,      LinqToDB.DataType.Decimal),
				new DataParameter("@IdCategoria", @IdCategoria, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[SpActualizarServicio]", parameters);
		}

		#endregion

		#region SpAgregarServicio

		public static int SpAgregarServicio(this PviProyectoFinalDB dataConnection, string @Nombre, string @Descripcion, decimal? @Precio, int? @IdCategoria, bool? @Estado)
		{
			var parameters = new []
			{
				new DataParameter("@Nombre",      @Nombre,      LinqToDB.DataType.VarChar)
				{
					Size = 100
				},
				new DataParameter("@Descripcion", @Descripcion, LinqToDB.DataType.Text)
				{
					Size = 2147483647
				},
				new DataParameter("@Precio",      @Precio,      LinqToDB.DataType.Decimal),
				new DataParameter("@IdCategoria", @IdCategoria, LinqToDB.DataType.Int32),
				new DataParameter("@Estado",      @Estado,      LinqToDB.DataType.Boolean)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_AgregarServicio]", parameters);
		}

		#endregion

		#region SpAlterdiagram

		public static int SpAlterdiagram(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]", parameters);
		}

		#endregion

		#region SpConsultarBitacoraPorCobro

		public static IEnumerable<SpConsultarBitacoraPorCobroResult> SpConsultarBitacoraPorCobro(this PviProyectoFinalDB dataConnection, int? @IdCobro)
		{
			var parameters = new []
			{
				new DataParameter("@IdCobro", @IdCobro, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarBitacoraPorCobroResult>("[dbo].[SpConsultarBitacoraPorCobro]", parameters);
		}

		public partial class SpConsultarBitacoraPorCobroResult
		{
			public DateTime Fecha        { get; set; }
			public string   Accion       { get; set; }
			public string   Detalle      { get; set; }
			public string   RealizadoPor { get; set; }
		}

		#endregion

		#region SpConsultarCasas

		public static IEnumerable<SpConsultarCasasResult> SpConsultarCasas(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpConsultarCasasResult>("[dbo].[sp_ConsultarCasas]");
		}

		public partial class SpConsultarCasasResult
		{
			[Column("id_casa")            ] public int      Id_casa             { get; set; }
			[Column("nombre_casa")        ] public string   Nombre_casa         { get; set; }
			[Column("metros_cuadrados")   ] public int      Metros_cuadrados    { get; set; }
			[Column("numero_habitaciones")] public int      Numero_habitaciones { get; set; }
			[Column("numero_banos")       ] public int      Numero_banos        { get; set; }
			[Column("precio")             ] public decimal  Precio              { get; set; }
			[Column("fecha_construccion") ] public DateTime Fecha_construccion  { get; set; }
			[Column("propietario")        ] public string   Propietario         { get; set; }
			[Column("estado")             ] public string   Estado              { get; set; }
		}

		#endregion

		#region SpConsultarCobro

		public static IEnumerable<SpConsultarCobroResult> SpConsultarCobro(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpConsultarCobroResult>("[dbo].[SpConsultarCobro]");
		}

		public partial class SpConsultarCobroResult
		{
			[Column("id_cobro")      ] public int    Id_cobro       { get; set; }
			[Column("nombre_casa")   ] public string Nombre_casa    { get; set; }
			[Column("nombre_cliente")] public string Nombre_cliente { get; set; }
			[Column("periodo")       ] public string Periodo        { get; set; }
			[Column("estado")        ] public string Estado         { get; set; }
		}

		#endregion

		#region SpConsultarCobrosUsuario

		public static IEnumerable<SpConsultarCobrosUsuarioResult> SpConsultarCobrosUsuario(this PviProyectoFinalDB dataConnection, int? @IdPersona)
		{
			var parameters = new []
			{
				new DataParameter("@IdPersona", @IdPersona, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarCobrosUsuarioResult>("[dbo].[SpConsultarCobrosUsuario]", parameters);
		}

		public partial class SpConsultarCobrosUsuarioResult
		{
			[Column("id_cobro")      ] public int    Id_cobro       { get; set; }
			[Column("nombre_casa")   ] public string Nombre_casa    { get; set; }
			[Column("nombre_cliente")] public string Nombre_cliente { get; set; }
			[Column("periodo")       ] public string Periodo        { get; set; }
			[Column("estado")        ] public string Estado         { get; set; }
		}

		#endregion

		#region SpConsultarDetalleCobro

		public static IEnumerable<SpConsultarDetalleCobroResult> SpConsultarDetalleCobro(this PviProyectoFinalDB dataConnection, int? @IdCobro)
		{
			var parameters = new []
			{
				new DataParameter("@IdCobro", @IdCobro, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarDetalleCobroResult>("[dbo].[SpConsultarDetalleCobro]", parameters);
		}

		public partial class SpConsultarDetalleCobroResult
		{
			[Column("id_cobro")         ] public int       Id_cobro          { get; set; }
			[Column("nombre_casa")      ] public string    Nombre_casa       { get; set; }
			[Column("id_persona")       ] public int       Id_persona        { get; set; }
			[Column("nombre_cliente")   ] public string    Nombre_cliente    { get; set; }
			[Column("mes")              ] public int       Mes               { get; set; }
			[Column("año")              ] public int       Año               { get; set; }
			[Column("estado")           ] public string    Estado            { get; set; }
			[Column("fecha_cancelacion")] public DateTime? Fecha_cancelacion { get; set; }
			[Column("monto")            ] public decimal   Monto             { get; set; }
		}

		#endregion

		#region SpConsultarServicios

		public static IEnumerable<SpConsultarServiciosResult> SpConsultarServicios(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpConsultarServiciosResult>("[dbo].[sp_ConsultarServicios]");
		}

		public partial class SpConsultarServiciosResult
		{
			[Column("id_servicio")     ] public int     Id_servicio      { get; set; }
			[Column("nombre_servicio") ] public string  Nombre_servicio  { get; set; }
			[Column("descripcion")     ] public string  Descripcion      { get; set; }
			[Column("precio")          ] public decimal Precio           { get; set; }
			[Column("nombre_categoria")] public string  Nombre_categoria { get; set; }
			[Column("estado")          ] public string  Estado           { get; set; }
		}

		#endregion

		#region SpConsultarServiciosPorCobro

		public static IEnumerable<SpConsultarServiciosPorCobroResult> SpConsultarServiciosPorCobro(this PviProyectoFinalDB dataConnection, int? @IdCobro)
		{
			var parameters = new []
			{
				new DataParameter("@IdCobro", @IdCobro, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarServiciosPorCobroResult>("[dbo].[SpConsultarServiciosPorCobro]", parameters);
		}

		public partial class SpConsultarServiciosPorCobroResult
		{
			public string Nombre   { get; set; }
			public int    Incluido { get; set; }
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]", parameters);
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]", parameters);
		}

		#endregion

		#region SpFiltrarCobrosEmpleado

		public static IEnumerable<SpFiltrarCobrosEmpleadoResult> SpFiltrarCobrosEmpleado(this PviProyectoFinalDB dataConnection, int? @IdCliente, int? @mes, int? @anno)
		{
			var parameters = new []
			{
				new DataParameter("@IdCliente", @IdCliente, LinqToDB.DataType.Int32),
				new DataParameter("@mes",       @mes,       LinqToDB.DataType.Int32),
				new DataParameter("@anno",      @anno,      LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpFiltrarCobrosEmpleadoResult>("[dbo].[SpFiltrarCobrosEmpleado]", parameters);
		}

		public partial class SpFiltrarCobrosEmpleadoResult
		{
			[Column("id_cobro")      ] public int    Id_cobro       { get; set; }
			[Column("nombre_casa")   ] public string Nombre_casa    { get; set; }
			[Column("nombre_cliente")] public string Nombre_cliente { get; set; }
			[Column("periodo")       ] public string Periodo        { get; set; }
			[Column("estado")        ] public string Estado         { get; set; }
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]", parameters);
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			[Column("version")   ] public int?   Version    { get; set; }
			[Column("definition")] public byte[] Definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]", parameters);
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpInactivarServicio

		public static int SpInactivarServicio(this PviProyectoFinalDB dataConnection, int? @IdServicio)
		{
			var parameters = new []
			{
				new DataParameter("@IdServicio", @IdServicio, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[SpInactivarServicio]", parameters);
		}

		#endregion

		#region SpInsertarCobroCompleto

		public static int SpInsertarCobroCompleto(this PviProyectoFinalDB dataConnection, int? @idCasa, int? @mes, int? @anno, int? @idUser, DataTable @serviciosSeleccionados)
		{
			var parameters = new []
			{
				new DataParameter("@id_casa",                @idCasa,                 LinqToDB.DataType.Int32),
				new DataParameter("@mes",                    @mes,                    LinqToDB.DataType.Int32),
				new DataParameter("@anno",                   @anno,                   LinqToDB.DataType.Int32),
				new DataParameter("@id_user",                @idUser,                 LinqToDB.DataType.Int32),
				new DataParameter("@serviciosSeleccionados", @serviciosSeleccionados, LinqToDB.DataType.Structured)
				{
					DbType = "[dbo].[ServicioList]"
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_InsertarCobroCompleto]", parameters);
		}

		#endregion

		#region SpLeerServicioPorId

		public static IEnumerable<SpLeerServicioPorIdResult> SpLeerServicioPorId(this PviProyectoFinalDB dataConnection, int? @IdServicio)
		{
			var parameters = new []
			{
				new DataParameter("@IdServicio", @IdServicio, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpLeerServicioPorIdResult>("[dbo].[sp_LeerServicioPorId]", parameters);
		}

		public partial class SpLeerServicioPorIdResult
		{
			[Column("id_servicio")     ] public int     Id_servicio      { get; set; }
			[Column("nombre")          ] public string  Nombre           { get; set; }
			[Column("descripcion")     ] public string  Descripcion      { get; set; }
			[Column("precio")          ] public decimal Precio           { get; set; }
			[Column("id_categoria")    ] public int     Id_categoria     { get; set; }
			[Column("nombre_categoria")] public string  Nombre_categoria { get; set; }
			[Column("estado")          ] public bool    Estado           { get; set; }
		}

		#endregion

		#region SpLoginUsuario

		public static IEnumerable<SpLoginUsuarioResult> SpLoginUsuario(this PviProyectoFinalDB dataConnection, string @Email, string @Contrasena)
		{
			var parameters = new []
			{
				new DataParameter("@Email",      @Email,      LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@Contrasena", @Contrasena, LinqToDB.DataType.VarChar)
				{
					Size = 255
				}
			};

			return dataConnection.QueryProc<SpLoginUsuarioResult>("[dbo].[sp_LoginUsuario]", parameters);
		}

		public partial class SpLoginUsuarioResult
		{
			[Column("login_exitoso")  ] public int    Login_exitoso   { get; set; }
			[Column("id_persona")     ] public int?   Id_persona      { get; set; }
			[Column("nombre_completo")] public string Nombre_completo { get; set; }
			[Column("es_empleado")    ] public int    Es_empleado     { get; set; }
		}

		#endregion

		#region SpObtenerCasasPorCliente

		public static IEnumerable<SpObtenerCasasPorClienteResult> SpObtenerCasasPorCliente(this PviProyectoFinalDB dataConnection, int? @IdCliente)
		{
			var parameters = new []
			{
				new DataParameter("@IdCliente", @IdCliente, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerCasasPorClienteResult>("[dbo].[SpObtenerCasasPorCliente]", parameters);
		}

		public partial class SpObtenerCasasPorClienteResult
		{
			[Column("id_casa")    ] public int    Id_casa     { get; set; }
			[Column("nombre_casa")] public string Nombre_casa { get; set; }
		}

		#endregion

		#region SpObtenerCategorias

		public static IEnumerable<SpObtenerCategoriasResult> SpObtenerCategorias(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerCategoriasResult>("[dbo].[sp_ObtenerCategorias]");
		}

		public partial class SpObtenerCategoriasResult
		{
			[Column("id_categoria")] public int    Id_categoria { get; set; }
			[Column("nombre")      ] public string Nombre       { get; set; }
		}

		#endregion

		#region SpObtenerClientesActivos

		public static IEnumerable<SpObtenerClientesActivosResult> SpObtenerClientesActivos(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerClientesActivosResult>("[dbo].[SpObtenerClientesActivos]");
		}

		public partial class SpObtenerClientesActivosResult
		{
			[Column("id_persona")     ] public int    Id_persona      { get; set; }
			[Column("nombre_completo")] public string Nombre_completo { get; set; }
		}

		#endregion

		#region SpObtenerCobroPorId

		public static IEnumerable<SpObtenerCobroPorIdResult> SpObtenerCobroPorId(this PviProyectoFinalDB dataConnection, int? @idCobro)
		{
			var parameters = new []
			{
				new DataParameter("@id_cobro", @idCobro, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerCobroPorIdResult>("[dbo].[sp_ObtenerCobroPorId]", parameters);
		}

		public partial class SpObtenerCobroPorIdResult
		{
			[Column("id_cobro")            ] public int       Id_cobro             { get; set; }
			[Column("mes")                 ] public int       Mes                  { get; set; }
			[Column("anno")                ] public int       Anno                 { get; set; }
			[Column("estado_cobro")        ] public string    Estado_cobro         { get; set; }
			[Column("monto")               ] public decimal   Monto                { get; set; }
			[Column("fecha_pagada")        ] public DateTime? Fecha_pagada         { get; set; }
			[Column("id_casa")             ] public int       Id_casa              { get; set; }
			[Column("nombre_casa")         ] public string    Nombre_casa          { get; set; }
			[Column("precio_casa")         ] public decimal   Precio_casa          { get; set; }
			[Column("numero_habitaciones") ] public int       Numero_habitaciones  { get; set; }
			[Column("numero_banos")        ] public int       Numero_banos         { get; set; }
			[Column("id_persona")          ] public int       Id_persona           { get; set; }
			[Column("propietario")         ] public string    Propietario          { get; set; }
			[Column("email_propietario")   ] public string    Email_propietario    { get; set; }
			[Column("telefono")            ] public string    Telefono             { get; set; }
			[Column("id_servicio")         ] public int       Id_servicio          { get; set; }
			[Column("nombre_servicio")     ] public string    Nombre_servicio      { get; set; }
			[Column("precio_servicio")     ] public decimal   Precio_servicio      { get; set; }
			[Column("descripcion_servicio")] public string    Descripcion_servicio { get; set; }
			[Column("id_bitacora")         ] public int?      Id_bitacora          { get; set; }
			[Column("detalle_bitacora")    ] public string    Detalle_bitacora     { get; set; }
			[Column("fecha_bitacora")      ] public DateTime? Fecha_bitacora       { get; set; }
			[Column("usuario_bitacora")    ] public string    Usuario_bitacora     { get; set; }
		}

		#endregion

		#region SpObtenerServiciosActivos

		public static IEnumerable<SpObtenerServiciosActivosResult> SpObtenerServiciosActivos(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerServiciosActivosResult>("[dbo].[SpObtenerServiciosActivos]");
		}

		public partial class SpObtenerServiciosActivosResult
		{
			[Column("id_servicio")] public int     Id_servicio { get; set; }
			[Column("nombre")     ] public string  Nombre      { get; set; }
			[Column("precio")     ] public decimal Precio      { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this PviProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, string @newDiagramname)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname",     @diagramname,    LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",        @ownerId,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @newDiagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]", parameters);
		}

		#endregion

		#region SpUpgraddiagrams

		public static int SpUpgraddiagrams(this PviProyectoFinalDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_upgraddiagrams]");
		}

		#endregion

		#region SpValidarCobroExistente

		public static IEnumerable<SpValidarCobroExistenteResult> SpValidarCobroExistente(this PviProyectoFinalDB dataConnection, int? @idCasa, int? @mes, int? @anno)
		{
			var parameters = new []
			{
				new DataParameter("@idCasa", @idCasa, LinqToDB.DataType.Int32),
				new DataParameter("@mes",    @mes,    LinqToDB.DataType.Int32),
				new DataParameter("@anno",   @anno,   LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpValidarCobroExistenteResult>("[dbo].[SpValidarCobroExistente]", parameters);
		}

		public partial class SpValidarCobroExistenteResult
		{
			public int Existe { get; set; }
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="[dbo].[fn_diagramobjects]", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Casa Find(this ITable<Casa> table, int IdCasa)
		{
			return table.FirstOrDefault(t =>
				t.IdCasa == IdCasa);
		}

		public static Categoria Find(this ITable<Categoria> table, int IdCategoria)
		{
			return table.FirstOrDefault(t =>
				t.IdCategoria == IdCategoria);
		}

		public static Cobro Find(this ITable<Cobro> table, int IdCobro)
		{
			return table.FirstOrDefault(t =>
				t.IdCobro == IdCobro);
		}

		public static DetalleCobro Find(this ITable<DetalleCobro> table, int Servicio, int IdCobro)
		{
			return table.FirstOrDefault(t =>
				t.Servicio == Servicio &&
				t.IdCobro  == IdCobro);
		}

		public static Persona Find(this ITable<Persona> table, int IdPersona)
		{
			return table.FirstOrDefault(t =>
				t.IdPersona == IdPersona);
		}

		public static Servicio Find(this ITable<Servicio> table, int IdServicio)
		{
			return table.FirstOrDefault(t =>
				t.IdServicio == IdServicio);
		}
	}
}
